name: IfChange

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ifchange:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: slnc/ifchange@v1
