name: Lint IfChange

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-ifchange:
    uses: ./.github/workflows/ifttt-lint-reusable.yml
    with:
      binary_source: cargo
      install_cmd: cargo install --path .
